"""Add bio and image_file to User model

Revision ID: 31b77bd563b4
Revises: 5f7e2e69adde
Create Date: 2025-06-19 11:56:41.990467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b77bd563b4'
down_revision = '5f7e2e69adde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_file', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_file')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
