"""Add description to StudyRoom

Revision ID: 6942880c7e91
Revises: 344585458d6b
Create Date: 2025-06-11 11:53:54.846160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6942880c7e91'
down_revision = '344585458d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_room', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
