name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # or "master" if that's your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker image to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: virtual-study-room          
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ''
